[package]
name = "dstspa"
version = "1.0.0"
edition = "2021"

[dependencies]
ron = "0.8.0"
markdown-it = "0.5.0"

[dependencies.serde]
version = "1.0.164"
features = ["derive"]

[dependencies.tagger]
git = "https://github.com/destinationspa/tagger"
branch = "unwrap"
